- hosts: 127.0.0.1
  pre_tasks:
  - name: "update"
    apt: 
      update_cache: yes
  tasks:
    - name: ensure nginx is at the latest version
      apt: name= nginx state=latest
    - name: start nginx
      service:
          name: nginx
          state: present
          update_cache: yes
